[project]
name = "01-health-and-wellness-planner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai-agents[litellm]>=0.1.0",
    "pydantic>=2.11.7",
    "strands>=0.1.0",
    "streamlit>=1.46.1",
]
